{
 "title": "HDFS - DataNode",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datanode",
    "query": "select distinct hostnode from t_node_metrics where appname='hdfs' and appcomponent='datanode'"
   }
  ]
 },
 "panels": [
  {
   "title": "DataNode Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hdfs_dn_metrics\nWHERE\n  datanode = '$datanode' AND\n  numvalue != 0 AND\n  modelertype LIKE 'DataNodeActivity-%'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JVMMetrics",
   "type": "graph",
   "description": "DataNodes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  metricname,\n  numvalue\nFROM t_hdfs_dn_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = 'JvmMetrics' AND\n  datanode = '$datanode'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DataSetState",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  metricname,\n  numvalue\nFROM t_hdfs_dn_metrics\nWHERE\n  modelertype = 'FSDatasetState' AND\n  numvalue != 0 AND\n  datanode = '$datanode'\nORDER BY 1"
    }
   ]
  }
 ]
}