{
 "title": "HIVE Server",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hs2",
    "query": "select distinct hostnode from t_node_metrics where appname='hive'"
   }
  ]
 },
 "panels": [
  {
   "title": "Hive Server Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = 'MetricsSystem,sub=Stats' AND\n  hs2node = '$hs2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Garbage Collectors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  modelertype = 'sun.management.GarbageCollectorImpl' AND\n  numvalue > 1 AND\n  hs2node = '$hs2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JMXGuage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = 'com.codahale.metrics.JmxReporterJmxGauge' AND\n  hs2node = '$hs2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JMXMeter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  hs2node = '$hs2' AND\n  modelertype = 'com.codahale.metrics.JmxReporterJmxMeter' AND\n  numvalue != 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JMXTimer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  hs2node = '$hs2' AND\n  modelertype = 'com.codahale.metrics.JmxReporterJmxTimer' AND\n  numvalue != 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JMXCounters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_hive_metrics\nWHERE\n  numvalue != 0 AND\n  hs2node = '$hs2' AND\n  modelertype = 'com.codahale.metrics.JmxReporterJmxCounter'\nORDER BY 1"
    }
   ]
  }
 ]
}