{
 "title": "YARN - ResourceManager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queuename",
    "query": "select distinct modelertype from t_yarn_rm_metrics where modelertype like 'QueueMetrics%'"
   }
  ]
 },
 "panels": [
  {
   "title": "ClusterMetrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_rm_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = 'ClusterMetrics'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JVMMetrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_rm_metrics\nWHERE\n  modelertype = 'JvmMetrics' AND\n  numvalue != 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CapacityScheduler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_rm_metrics\nWHERE\n  modelertype = 'CapacitySchedulerMetrics' AND\n  numvalue != 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Queue Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_rm_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = '$queuename'\nORDER BY 1"
    }
   ]
  }
 ]
}