{
 "title": "YARN - NodeManagers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodemanager",
    "query": "select distinct hostnode from t_node_metrics where appname='yarn' and appcomponent='nm'"
   }
  ]
 },
 "panels": [
  {
   "title": "NodeManagerMetrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_nm_metrics\nWHERE\n  numvalue != 0 AND\n  nmnode = '$nodemanager' AND\n  modelertype = 'NodeManagerMetrics'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "JVMMetrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_nm_metrics\nWHERE\n  numvalue != 0 AND\n  nmnode = '$nodemanager' AND\n  modelertype = 'JvmMetrics'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ShuffleMetrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  collection_ts AS \"time\",\n  numvalue,\n  metricname\nFROM t_yarn_nm_metrics\nWHERE\n  numvalue != 0 AND\n  modelertype = 'ShuffleMetrics' AND\n  nmnode = '$nodemanager'\nORDER BY 1"
    }
   ]
  }
 ]
}