
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'StartupProgress', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'FSNamesystem', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'RpcDetailedActivityForPort', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'MetricsSystem,sub=Stats', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'NameNodeActivity', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'org.apache.hadoop.hdfs.server.namenode.FSNamesystem', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'RpcActivityForPort', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'namenode', 'UgiMetrics', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'MetricsSystem,sub=Stats', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'FSDatasetState', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'RpcDetailedActivityForPort', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'RpcActivityForPort', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'DataNodeActivity-', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hdfs', 'datanode', 'UgiMetrics', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=Balancer', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=AssignmentManager', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'MetricsSystem,sub=Stats', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=FileSystem', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'RegionServer,sub=IO', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=Quotas', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=Server', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'Master,sub=IPC', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'hmaster', 'UgiMetrics', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'MetricsSystem,sub=Stats', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=IO', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=Regions', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=Replication', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=TableLatencies', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=WAL', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=Tables', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=Server', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=Memory', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'RegionServer,sub=IPC', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('hbase', 'regionserver', 'UgiMetrics', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxCounter', '', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'sun.management.GarbageCollectorImpl', 'java.lang:type=GarbageCollector', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxGauge', '', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxMeter', '', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'MetricsSystem,sub=Stats', '', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'UgiMetrics', '', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'sun.management.OperatingSystemImpl', '', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_runTasks', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=hs2_submitted_queries', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_TezRunDag', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_hs2_sql_operation_PENDING', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_RenameOrMoveFiles', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_compile', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_optimizer', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=hs2_compiling_queries', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_waitCompile', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_hs2_operation_INITIALIZED', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_doAuthorization', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_acquireReadWriteLocks', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=hs2_executing_queries', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_Driver.execute', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_hs2_sql_operation_RUNNING', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_Driver.run', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_releaseLocks', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_hs2_operation_RUNNING', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_hs2_operation_PENDING', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_parse', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_semanticAnalyze', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_TezBuildDag', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_TezCompiler', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_TezSubmitDag', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_TezSubmitToRunningDag', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, mtypename, is_active) values('hive', 'hs2', 'com.codahale.metrics.JmxReporter$JmxTimer', 'metrics:name=api_RemoveTempOrDuplicateFiles', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'QueueMetrics,', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'CapacitySchedulerMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'ClusterMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'RpcDetailedActivityFor', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'UgiMetrics', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'sun.management.ThreadImpl', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'MetricsSystem,sub=Stats', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'rm', 'RpcActivityFor', 'N');

Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'JvmMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'sun.management.OperatingSystemImpl', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'NodeManagerMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'ShuffleMetrics', 'Y');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'sun.management.ThreadImpl', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'RpcDetailedActivityFor', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'RpcActivityFor', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'UgiMetrics', 'N');
Insert into t_coll_metrics (appname, appcomponent, modelerType, is_active) values('yarn', 'nm', 'MetricsSystem,sub=Stats', 'N');
